package net.oktawia.crazyae2addons.defs;

import appeng.core.localization.LocalizationEnum;

public enum LangDefs implements LocalizationEnum {
    LANG("key", "val"),
    PROVIDER_MAX("gui.crazyae2addons.provider_max", "Maximum capacity reached!"),
    CRAZY_PROVIDER_CAPACITY_TOOLTIP("gui.crazyae2addons.crazy_provider_capacity_tooltip", "Capacity: "),
    AMOUNT("gui.crazyae2addons.amount", "Amount"),
    TARGET("gui.crazyae2addons.target", "Target"),
    CRAFTING_SCHEDULER_TARGET("gui.crazyae2addons.crafting_scheduler_target", "Target"),
    MOD_NAME("gui.crazyae2addons.mod_name", "Crazy AE2 Addons"),
    SKIP_MISSING("gui.crazyae2addons.skip_missing", "Skip Missing"),
    SKIP_MISSING_TOOLTIP("gui.crazyae2addons.skip_missing_tooltip", "Skip blocks that are missing from the network"),
    MOVE_FORWARD("gui.crazyae2addons.move_forward", "Move forward"),
    MOVE_BACKWARD("gui.crazyae2addons.move_backward", "Move backward"),
    MOVE_RIGHT("gui.crazyae2addons.move_right", "Move right"),
    MOVE_LEFT("gui.crazyae2addons.move_left", "Move left"),
    MOVE_UP("gui.crazyae2addons.move_up", "Move up"),
    MOVE_DOWN("gui.crazyae2addons.move_down", "Move down"),
    SHOW_PREVIEW("gui.crazyae2addons.show_preview", "Show Preview"),
    HIDE_PREVIEW("gui.crazyae2addons.hide_preview", "Hide Preview"),
    AXIS_X("gui.crazyae2addons.axis_x", "X"),
    AXIS_Y("gui.crazyae2addons.axis_y", "Y"),
    AXIS_Z("gui.crazyae2addons.axis_z", "Z"),
    PATTERN("gui.crazyae2addons.pattern", "Pattern"),
    PATTERNS("gui.crazyae2addons.patterns", "Patterns"),
    OFFSET("gui.crazyae2addons.offset", "Offset"),
    MISSING("gui.crazyae2addons.missing", "Missing:"),
    CONFIRM("gui.crazyae2addons.confirm", "Save"),
    FLIP_HORIZONTAL("gui.crazyae2addons.flip_horizontal", "Flip Horizontal"),
    FLIP_VERTICAL("gui.crazyae2addons.flip_vertical", "Flip Vertical"),
    ROTATE_CW("gui.crazyae2addons.rotate_cw", "Rotate CW"),
    RENAME("gui.crazyae2addons.rename", "Rename"),
    DELAY("gui.crazyae2addons.delay", "Tick Delay"),
    PROGRAM_SAVED("gui.crazyae2addons.program_saved", "Pattern saved!"),
    SYNTAX_ERROR("gui.crazyae2addons.syntax_error", "Syntax Error!"),
    PROGRAM_INVALID("gui.crazyae2addons.program_invalid", "Pattern is invalid"),
    PROGRAM_NO_CODE("gui.crazyae2addons.program_no_code", "No program loaded"),
    PROGRAM_CHANGES_FAILED("gui.crazyae2addons.program_changes_failed", "Failed to apply changes"),
    CORNER_SET_A("gui.crazyae2addons.corner_set_a", "Corner A set"),
    CORNER_SET_B("gui.crazyae2addons.corner_set_b", "Corner B set (origin)"),
    CORNER_RESET("gui.crazyae2addons.corner_reset", "Corners reset"),
    ENERGY_NEEDED("gui.crazyae2addons.energy_needed", "Energy needed: "),
    NOTHING("gui.crazyae2addons.nothing", "Nothing"),
    AMPERE_METER_DIRECTION_LEFT_TO_RIGHT("gui.crazyae2addons.ampere_meter_direction_left_to_right", "Send power from left to right"),
    AMPERE_METER_DIRECTION_RIGHT_TO_LEFT("gui.crazyae2addons.ampere_meter_direction_right_to_left", "Send power from right to left"),
    MIN("gui.crazyae2addons.min", "Min"),
    MAX("gui.crazyae2addons.max", "Max"),
    FE_PER_TICK("gui.crazyae2addons.fe_per_tick", "FE/t"),
    FE_PER_TICK_OR_AMPERES("gui.crazyae2addons.fe_per_tick_or_amperes", "FE/t or Amperes"),
    CONFIG("gui.crazyae2addons.config", "Config"),
    EJECTOR_LOAD_PATTERN("gui.crazyae2addons.ejector_load_pattern", "Load settings from pattern"),
    EJECTOR_MIDDLE_CLICK("gui.crazyae2addons.ejector_middle_click", "Middle mouse button to set amount"),
    OUTPUT("gui.crazyae2addons.output", "Output"),
    VOLTAGE("gui.crazyae2addons.voltage", "Voltage"),
    AMPERAGE("gui.crazyae2addons.amperage", "Amperage"),
    CHUNK_SIZE("gui.crazyae2addons.chunk_size", "Chunk Size (mB)"),
    REDSTONE_TERMINAL_SEARCH("gui.crazyae2addons.redstone_terminal_search", "Search"),
    OUT_OF_RANGE("gui.crazyae2addons.out_of_range", "Wireless out of range"),
    RIGHT("gui.crazyae2addons.right", "Right"),
    LEFT("gui.crazyae2addons.left", "Left"),
    UP("gui.crazyae2addons.up", "Up"),
    DOWN("gui.crazyae2addons.down", "Down"),
    FORWARDS("gui.crazyae2addons.forwards", "Forwards"),
    BACKWARDS("gui.crazyae2addons.backwards", "Backwards"),
    ALWAYS("gui.crazyae2addons.always", "Always"),
    EQUALS("gui.crazyae2addons.equals", "Equals"),
    NOT_EQUALS("gui.crazyae2addons.not_equals", "Not Equals"),
    BREAK("gui.crazyae2addons.break", "Break"),
    PLACE("gui.crazyae2addons.place", "Place"),
    WIDTH("gui.crazyae2addons.width", "Width"),
    HEIGHT("gui.crazyae2addons.height", "Height"),
    DEPTH("gui.crazyae2addons.depth", "Depth"),
    ACTION("gui.crazyae2addons.action", "Action"),
    CONDITION("gui.crazyae2addons.condition", "Condition"),
    CHECK("gui.crazyae2addons.check", "Check"),
    GENERATE("gui.crazyae2addons.generate", "Generate"),
    INSERT_TOKEN("gui.crazyae2addons.insert_token", "Insert Token"),
    INSERT("gui.crazyae2addons.insert", "Insert"),
    BACK("gui.crazyae2addons.back", "Back"),
    ICON("gui.crazyae2addons.icon", "Icon"),
    STOCK("gui.crazyae2addons.stock", "Stock"),
    DELTA("gui.crazyae2addons.delta", "Delta"),
    SAVE("gui.crazyae2addons.save", "Save"),
    JOIN_DISPLAYS("gui.crazyae2addons.join_displays", "Join Displays"),
    ADD_MARGIN("gui.crazyae2addons.add_margin", "Add 3% Margin"),
    CENTER_TEXT("gui.crazyae2addons.center_text", "Center Text"),
    ITEM_ID_LABEL("gui.crazyae2addons.item_id_label", "Item ID:"),
    TYPE_LABEL("gui.crazyae2addons.type_label", "Type:"),
    DIVISOR_LABEL("gui.crazyae2addons.divisor_label", "Divisor:"),
    PER_LABEL("gui.crazyae2addons.per_label", "Per:"),
    WINDOW_LABEL("gui.crazyae2addons.window_label", "Window:"),
    ANY("gui.crazyae2addons.any", "Any"),
    KEY_TYPES_COLLAPSED("gui.crazyae2addons.key_types_collapsed", "Key types \u25bc"),
    KEY_TYPES_EXPANDED("gui.crazyae2addons.key_types_expanded", "Key types \u25b2"),
    TYPES_HEADER("gui.crazyae2addons.types_header", "Types"),
    DIV_RAW("gui.crazyae2addons.div_raw", "raw"),
    DIV_10("gui.crazyae2addons.div_10", "/10"),
    DIV_100("gui.crazyae2addons.div_100", "/100"),
    DIV_1K("gui.crazyae2addons.div_1k", "/1k"),
    DIV_10K("gui.crazyae2addons.div_10k", "/10k"),
    DIV_100K("gui.crazyae2addons.div_100k", "/100k"),
    DIV_1M("gui.crazyae2addons.div_1m", "/1M"),
    UNIT_TICKS("gui.crazyae2addons.unit_ticks", "t"),
    UNIT_SECONDS("gui.crazyae2addons.unit_seconds", "s"),
    UNIT_MINUTES("gui.crazyae2addons.unit_minutes", "m"),
    DISPLAY_IMAGES("gui.crazyae2addons.display_images", "Display Images"),
    IMAGES("gui.crazyae2addons.images", "Images"),
    ADD("gui.crazyae2addons.add", "Add"),
    REMOVE("gui.crazyae2addons.remove", "Remove"),
    APPLY("gui.crazyae2addons.apply", "Apply"),
    PICK_FILE("gui.crazyae2addons.pick_file", "Pick File"),
    PASTE("gui.crazyae2addons.paste", "Paste"),
    SELECTED("gui.crazyae2addons.selected", "Selected"),
    BACKGROUND_COLOR("gui.crazyae2addons.background_color", "Background Color"),
    CHANGE_SELECTED_TEXT_COLOR("gui.crazyae2addons.change_selected_text_color", "Change Selected Text Color"),
    UNSAVED_CHANGES_TITLE("gui.crazyae2addons.unsaved_changes_title", "Are you sure?"),
    UNSAVED_CHANGES_TEXT("gui.crazyae2addons.unsaved_changes_text", "You have not saved the changes."),
    IMAGE_UPLOAD_OK("gui.crazyae2addons.image_upload_ok", "Image uploaded"),
    IMAGE_UPLOAD_CANCELLED("gui.crazyae2addons.image_upload_cancelled", "Image selection cancelled"),
    IMAGE_UPLOAD_CLIPBOARD_EMPTY("gui.crazyae2addons.image_upload_clipboard_empty", "Clipboard is empty"),
    IMAGE_UPLOAD_INVALID_PATH("gui.crazyae2addons.image_upload_invalid_path", "Clipboard does not contain a valid file path"),
    IMAGE_UPLOAD_INVALID_IMAGE("gui.crazyae2addons.image_upload_invalid_image", "Unsupported or corrupted image file"),
    IMAGE_UPLOAD_TOO_BIG("gui.crazyae2addons.image_upload_too_big", "Image is too large (%s x %s)"),
    IMAGE_UPLOAD_TOO_LARGE("gui.crazyae2addons.image_upload_too_large", "Image file is too large (%s bytes)"),
    IMAGE_UPLOAD_FAILED("gui.crazyae2addons.image_upload_failed", "Failed to upload image"),
    PICK_FILE_TOOLTIP("gui.crazyae2addons.pick_file_tooltip", "Pick and upload image"),
    REMOVE_IMAGE_TOOLTIP("gui.crazyae2addons.remove_image_tooltip", "Remove selected image"),
    APPLY_IMAGE_SETTINGS_TOOLTIP("gui.crazyae2addons.apply_image_settings_tooltip", "Apply image position and size"),
    IMAGE_LIST_TOOLTIP("gui.crazyae2addons.image_list_tooltip", "Uploaded images"),
    X_PERCENT("gui.crazyae2addons.x_percent", "X %"),
    Y_PERCENT("gui.crazyae2addons.y_percent", "Y %"),
    WIDTH_PERCENT("gui.crazyae2addons.width_percent", "Width %"),
    HEIGHT_PERCENT("gui.crazyae2addons.height_percent", "Height %"),
    X_PERCENT_TOOLTIP("gui.crazyae2addons.x_percent_tooltip", "Horizontal position in percent. 0 = left edge, 100 = right edge"),
    Y_PERCENT_TOOLTIP("gui.crazyae2addons.y_percent_tooltip", "Vertical position in percent. 0 = top edge, 100 = bottom edge"),
    WIDTH_PERCENT_TOOLTIP("gui.crazyae2addons.width_percent_tooltip", "Image width in percent of the whole display"),
    HEIGHT_PERCENT_TOOLTIP("gui.crazyae2addons.height_percent_tooltip", "Image height in percent of the whole display"),
    SCALE_PERCENT("gui.crazyae2addons.scale_percent", "Scale %"),
    SCALE_PERCENT_TOOLTIP("gui.crazyae2addons.scale_percent_tooltip", "Image scale in percent");


    private final String key;
    private final String value;

    LangDefs(String key, String value) {
        this.key = key;
        this.value = value;
    }

    @Override
    public String getTranslationKey() {
        return key;
    }

    @Override
    public String getEnglishText() {
        return value;
    }
}