name: Build Jar && Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Build with Gradle Wrapper
        run: ./gradlew build --no-daemon --build-cache

      - name: Set VERSION
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            echo "VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
          else
            echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          fi

      - name: Find Jar file
        id: find_jar
        run: |
          FILE=$(find build/libs -maxdepth 1 -type f -name '*.jar' ! -name '*all.jar')
          if [ -z "$FILE" ]; then
            echo "No jar file found" >&2
            exit 1
          fi
          echo "FILE_NAME=${FILE}" >> $GITHUB_ENV

      - name: Upload Release Asset
        uses: yakuhzi/github-release@4.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ env.FILE_NAME }}
          asset-name: CrazyAE2Addons-${{ env.VERSION }}.jar
          app-name: CrazyAE2Addons-${{ env.VERSION }}.jar
