
name: build jar and create release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
      
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build
      
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: CrazyAE2Addons
        path: build/libs/*[!all].jar

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
  
    steps:
    - uses: actions/checkout@v4
    - name: Download JAR artifact
      uses: actions/download-artifact@v4
      with:
        name: CrazyAE2Addons
        path: build/libs/
  
    - name: Set VERSION
      shell: bash
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
          echo "VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
        else
          echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
        fi
  
    - name: Create Release && Upload
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        artifacts: CrazyAE2Adoons-v${{ env.VERSION }}.jar
        generateReleaseNotes: true
