package net.oktawia.crazyae2addonslite.defs;

import appeng.core.localization.LocalizationEnum;

public enum LangDefs implements LocalizationEnum {
    PROVIDER_MAX("gui.crazyae2addons.provider_max", "Reached the max size of that pattern provider"),
    BUILDER_PATTERN_SAVED("gui.crazyae2addons.builder_pattern_saved", "Saved pattern. Length: "),
    BUILDER_PATTERN_ERROR("gui.crazyae2addons.builder_pattern_error", "Could not save this structure"),
    BUILDER_PATTERN_CORNER_1("gui.crazyae2addons.builder_corner_1", "Corner 1 set!"),
    BUILDER_PATTERN_CORNER_2("gui.crazyae2addons.builder_corner_2", "Corner 2 set! (origin)"),
    BUILDER_PATTERN_CORNER_3("gui.crazyae2addons.builder_corner_3", "Corner 1 set! (reset)"),
    BUILDER_PATTERN_NO_PROGRAM("gui.crazyae2addons.builder_pattern_no_program", "No program"),
    BUILDER_PATTERN_FAILED_CHANGES("gui.crazyae2addons.builder_pattern_failed_changes", "Failed to save changes"),
    CRAZY_PROVIDER_CAPACITY_TOOLTIP("gui.crazyae2addons.crazy_provider_capacity_tooltip", "Capacity: "),
    COPY_PASTE_NOT_LINKED("gui.crazyae2addons.copy_paste_not_linked", "Not linked to any AE2 grid."),
    COPY_PASTE_NOT_LOADED("gui.crazyae2addons.copy_paste_not_loaded", "Linked dimension not found/loaded."),
    COPY_PASTE_NO_AP("gui.crazyae2addons.copy_paste_ap_missing", "No Wireless Access Point at linked position."),
    COPY_PASTE_NO_GRID("gui.crazyae2addons.copy_paste_no_grid", "AE2 grid not found."),
    COPY_PASTE_NO_GRID_POWER("gui.crazyae2addons.copy_paste_no_grid_power", "AE2 grid is not powered."),
    COPY_PASTE_SCHEDULING("gui.crazyae2addons.copy_paste_scheduling", "Scheduling crafts."),
    COPY_PASTE_CAN_NOT_CRAFT("gui.crazyae2addons.copy_paste_cannot_craft", "Can not craft all required items."),
    COPY_PASTE_SELECT_CORNERS("gui.crazyae2addons.copy_paste_select_corners", "Select corners first"),
    COPY_PASTE_ERROR_SAVING("gui.crazyae2addons.error_saving", "Could not save this structure"),
    COPY_PASTE_NO_STRUCTURE("gui.crazyae2addons.copy_paste_no_structure", "No stored structure"),
    CUT_PASTE_FIRST("gui.crazyae2addons.cut_paste_first", "Paste current structure first"),
    CANCEL_ALL_CRAFTING("gui.crazyae2addons.cancel_all_crafting", "Cancel All Crafting Jobs"),
    MOB_KEY("gui.crazyae2addons.mob_key", "Mobs"),
    AMPERE_METER_1("gui.crazyae2addons.ampere_meter_1", "Send power from left to right"),
    AMPERE_METER_2("gui.crazyae2addons.ampere_meter_2", "Send power from right to left"),
    BUILDER_SKIP("gui.crazyae2addons.builder_skip", "Skip"),
    BUILDER_SKIP_TOOLTIP("gui.crazyae2addons.builder_skip_tooltip", "Start building even if not all blocks are available"),
    BUILDER_OFFSET_FRONT("gui.crazyae2addons.builder_offset_front", "Add 1 offset to FRONT"),
    BUILDER_OFFSET_BACK("gui.crazyae2addons.builder_offset_back", "Add 1 offset to BACK"),
    BUILDER_OFFSET_RIGHT("gui.crazyae2addons.builder_offset_right", "Add 1 offset to RIGHT"),
    BUILDER_OFFSET_LEFT("gui.crazyae2addons.builder_offset_left", "Add 1 offset to LEFT"),
    BUILDER_OFFSET_UP("gui.crazyae2addons.builder_offset_up", "Add 1 offset to UP"),
    BUILDER_OFFSET_DOWN("gui.crazyae2addons.builder_offset_down", "Add 1 offset to DOWN"),
    BUILDER_PREVIEW_HIDE("gui.crazyae2addons.builder_preview_hide", "Hide preview"),
    BUILDER_PREVIEW_SHOW("gui.crazyae2addons.builder_preview_show", "Show preview"),
    ENCHANTER_LAPIS_ON("gui.crazyae2addons.enchanter_lapis_on", "Automatic lapis supply: Enabled"),
    ENCHANTER_LAPIS_OFF("gui.crazyae2addons.enchanter_lapis_off", "Automatic lapis supply: Disabled"),
    ENCHANTER_BOOK_ON("gui.crazyae2addons.enchanter_book_on", "Automatic books supply: Enabled"),
    ENCHANTER_BOOK_OFF("gui.crazyae2addons.enchanter_book_off", "Automatic books supply: Disabled"),
    ENCHANTER_CHEAP("gui.crazyae2addons.enchanter_cheap", "Cheap enchantment\nApply low-level enchant (cost: 1)"),
    ENCHANTER_MEDIUM("gui.crazyae2addons.enchanter_medium", "Medium enchantment\nApply mid-level enchant (cost: 2)"),
    ENCHANTER_EXP("gui.crazyae2addons.enchanter_exp", "Expensive enchantment\nApply powerful enchant (cost: 3)"),
    BUILDER_PATTERN_DELAY("gui.crazyae2addons.builder_pattern_delay", "Amount of ticks to wait after each action"),
    BUILDER_PATTERN_CONFIRM("gui.crazyae2addons.builder_pattern_confirm", "Confirm"),
    BUILDER_PATTERN_PROGRAM("gui.crazyae2addons.builder_pattern_program", "Input program"),
    BUILDER_PATTERN_FLIP_H("gui.crazyae2addons.builder_pattern_flip_h", "Horizontal flip"),
    BUILDER_PATTERN_FLIP_V("gui.crazyae2addons.builder_pattern_flip_v", "Vertical flip"),
    BUILDER_PATTERN_ROTATE("gui.crazyae2addons.builder_pattern_rotate", "Rotate by 90 deg"),
    CHUNKY_P2P_DESC("gui.crazyae2addons.chunky_p2p_desc", "Set chunk size in mB"),
    CHUNKY_P2P_SAVE("gui.crazyae2addons.chunky_p2p_save", "Save"),
    CPU_PRIO_SAVE("gui.crazyae2addons.cpu_prio_save", "Save"),
    CRAFTING_SCHEDULER_AMOUNT("gui.crazyae2addons.c_scheduler_amount", "Amount"),
    CALCULATOR_1("gui.crazyae2addons.calculator_equation", "Equation"),
    CALCULATOR_2("gui.crazyae2addons.calculator_result", "Result"),
    EMITER_MULT("gui.crazyae2addons.emiter_mult", "Multiplier"),
    EMITER_MULT_CHECKBOX("gui.crazyae2addons.emiter_mult_checkbox", "Multiply instead of set value"),
    MODIFIER_CIRCUIT_DESC("gui.crazyae2addons.modifier_circuit_desc", "Enter circuit number (0–32)"),
    MODIFIER_TOOLTIP("gui.crazyae2addons.modifier_tooltip", "Encode circuit"),
    MODIFIER_CIRCUIT_TOOLTIP("gui.crazyae2addons.modifier_circuit_tooltip", "Set circuit: %s"),
    PATTERN_MULT_CONFIRM("gui.crazyae2addons.pattern_mult_confirm", "Multiply all patterns by selected value"),
    PATTERN_MULT_CLEAR("gui.crazyae2addons.pattern_mult_clear", "Clear all patterns"),
    PATTERN_MULT_SET_CIRCUIT("gui.crazyae2addons.pattern_mult_set_circuit", "Set selected circuit to all patterns"),
    PATTERN_MULT_CIRCUIT_INPUT("gui.crazyae2addons.pattern_mult_circuit_input", "Input desired circuit number (0-32)"),
    PATTERN_MULT_MULTIPLIER("gui.crazyae2addons.pattern_mult_multiplier", "Multiplier"),
    PATTERN_MULT_VALUE_TOOLTIP("gui.crazyae2addons.pattern_mult_value_tooltip", "Input the amount by which you want to multiply your patterns, can also be an equation like 2*(3/4)"),
    PATTERN_MULT_LIMIT("gui.crazyae2addons.pattern_mult_limit", "Limit above which patterns wont get multiplied, 0 means limit disabled"),
    DISPLAY_TYPE_HERE("gui.crazyae2addons.display_type_here", "Type here"),
    DISPLAY_SUBMIT("gui.crazyae2addons.display_submit", "Submit"),
    DISPLAY_JOIN("gui.crazyae2addons.display_join", "Join with adjacent displays"),
    DISPLAY_CENTER("gui.crazyae2addons.display_center", "Center text"),
    DISPLAY_MARGIN("gui.crazyae2addons.display_margin", "3% margin around the text"),
    EJECTOR_LOAD_PATTERN("gui.crazyae2addons.ejector_load_pattern", "Load settings from pattern"),
    EJECTOR_MULTIPLIER_TOOLTIP("gui.crazyae2addons.ejector_multiplier_tooltip", "Multiplier applied to all items"),
    EJECTOR_NOTHING("gui.crazyae2addons.ejector_nothing", "nothing"),
    EJECTOR_MIDDLE_CLICK("gui.crazyae2addons.ejector_middle_click", "Middle mouse button to set amount"),
    ENTROPY_PREVIEW_TOOLTIP("gui.crazyae2addons.entropy_preview_tooltip", "Enable/Disable preview"),
    ENTROPY_PREVIEW_LABEL("gui.crazyae2addons.entropy_preview_label", "Preview: "),
    ENTITY_TICKER_ENERGY("gui.crazyae2addons.entity_ticker_energy", "Energy Usage: %s FE/t"),
    ENTITY_TICKER_SPEED("gui.crazyae2addons.entity_ticker_speed", "Current multiplier: %d"),
    ENTITY_TICKER_INFO_1("gui.crazyae2addons.entity_ticker_info_1", "Each card multiplies"),
    ENTITY_TICKER_INFO_2("gui.crazyae2addons.entity_ticker_info_2", "machines speed by 4"),
    GADGET_FLIP_H("gui.crazyae2addons.gadget_flip_h", "Horizontal flip"),
    GADGET_FLIP_V("gui.crazyae2addons.gadget_flip_v", "Vertical flip"),
    GADGET_ROTATE("gui.crazyae2addons.gadget_rotate", "Rotate by 90 deg"),
    MOBFARM_PREVIEW_TOOLTIP("gui.crazyae2addons.mobfarm_preview_tooltip", "Enable/Disable preview"),
    MOBFARM_ITEM_USE("gui.crazyae2addons.mobfarm_item_use", "Item to use:"),
    MOBFARM_PREVIEW_LABEL("gui.crazyae2addons.mobfarm_preview_label", "Preview: "),
    MOB_KEY_SEARCH("gui.crazyae2addons.mob_key_search", "Search mob..."),
    MOB_KEY_SELECTED("gui.crazyae2addons.mob_key_selected", "Selected"),
    NBT_EXPORT_CONFIRM("gui.crazyae2addons.nbt_export_confirm", "Confirm"),
    NBT_EXPORT_INPUT("gui.crazyae2addons.nbt_export_input", "Input filter"),
    NBT_EXPORT_LOAD("gui.crazyae2addons.nbt_export_load", "Load selected item's NBT"),
    NBT_STORAGE_CONFIRM("gui.crazyae2addons.nbt_storage_confirm", "Confirm"),
    NBT_STORAGE_INPUT("gui.crazyae2addons.nbt_storage_input", "Input filter"),
    NBT_STORAGE_LOAD("gui.crazyae2addons.nbt_storage_load", "Load selected item's NBT"),
    NBT_VIEW_CELL_TITLE("gui.crazyae2addons.nbt_view_cell_title", "NBT View Cell"),
    NBT_VIEW_CELL_CONFIRM("gui.crazyae2addons.nbt_view_cell_confirm", "Confirm"),
    NBT_VIEW_CELL_INPUT("gui.crazyae2addons.nbt_view_cell_input", "Input filter"),
    PENROSE_EXTRACT("gui.crazyae2addons.penrose_extract", "Extract singularities"),
    PENROSE_INSERT("gui.crazyae2addons.penrose_insert", "Insert singularities"),
    PENROSE_STORE_POWER("gui.crazyae2addons.penrose_store_power", "Store power"),
    PENROSE_POWER_AE("gui.crazyae2addons.penrose_power_ae", "as AE in the network power"),
    PENROSE_POWER_FE("gui.crazyae2addons.penrose_power_fe", "as FE in the multiblock"),
    PENROSE_PREVIEW_TOGGLE("gui.crazyae2addons.penrose_preview_toggle", "Enable/Disable preview"),
    PENROSE_CHANGE_TIER("gui.crazyae2addons.penrose_change_tier", "Change preview tier"),
    PENROSE_GENERATION("gui.crazyae2addons.penrose_generation", "Power Generation"),
    PENROSE_AMOUNT_FE("gui.crazyae2addons.penrose_amount_fe", "%s FE/t"),
    PENROSE_TIER_LABEL("gui.crazyae2addons.penrose_tier_label", "Tier: "),
    PENROSE_PREVIEW_STATUS("gui.crazyae2addons.penrose_preview_status", "Preview: %s, preview tier: %s"),
    REDSTONE_EMITTER_NAME("gui.crazyae2addons.redstone_emitter_name", "Name"),
    REDSTONE_TERMINAL_SEARCH("gui.crazyae2addons.redstone_terminal_search", "Search"),
    REINFORCED_CONDENSER_SINGULARITIES("gui.crazyae2addons.reinforced_condenser_singularities", "Stored singularities"),
    REINFORCED_CONDENSER_CELLS("gui.crazyae2addons.reinforced_condenser_cells", "Stored storage cells"),
    RESEARCH_STORED_ENERGY("gui.crazyae2addons.research_stored_energy", "Stored Energy"),
    RESEARCH_STORED_FLUID("gui.crazyae2addons.research_stored_fluid", "Stored Fluid"),
    RESEARCH_RECIPE_PROGRESS("gui.crazyae2addons.research_recipe_progress", "Recipe Progress"),
    RESEARCH_DEV_UNLOCK("gui.crazyae2addons.research_dev_unlock", "Write all research to disk"),
    RESEARCH_PREVIEW_HIDE("gui.crazyae2addons.research_preview_hide", "Hide preview"),
    RESEARCH_PREVIEW_SHOW("gui.crazyae2addons.research_preview_show", "Show preview"),
    RESEARCH_LOADING("gui.crazyae2addons.research_loading", "Loading..."),
    TAG_VIEW_CELL_TITLE("gui.crazyae2addons.tag_view_cell_title", "Tag View Cell"),
    TAG_VIEW_CELL_CONFIRM("gui.crazyae2addons.tag_view_cell_confirm", "Confirm"),
    TAG_VIEW_CELL_INPUT("gui.crazyae2addons.tag_view_cell_input", "Input filter"),
    WIRELESS_REDSTONE_SEARCH("gui.crazyae2addons.wireless_redstone_search", "Search"),
    CRADLE_LAYER_PREFIX("gui.crazyae2addons.cradle_layer_prefix", "L:"),
    CRADLE_LAYER_ALL("gui.crazyae2addons.cradle_layer_all", "ALL"),
    CRADLE_LAYER_TOOLTIP("gui.crazyae2addons.cradle_layer_tooltip", "Change layer visibility"),
    CRADLE_TOGGLE_LABEL("gui.crazyae2addons.cradle_toggle_label", "Cradle"),
    CRADLE_TOGGLE_ON("gui.crazyae2addons.cradle_on", "ON"),
    CRADLE_TOGGLE_OFF("gui.crazyae2addons.cradle_off", "OFF"),
    CRADLE_TOGGLE_TOOLTIP("gui.crazyae2addons.cradle_toggle_tooltip", "Toggle cradle visibility"),
    CRADLE_INPUTS("gui.crazyae2addons.cradle_inputs", "Inputs"),
    CRADLE_OUTPUT("gui.crazyae2addons.cradle_output", "Output"),
    CRAZY_PREVIEW_LAYER_PREFIX("gui.crazyae2addons.crazy_preview_layer_prefix", "L:"),
    CRAZY_PREVIEW_LAYER_ALL("gui.crazyae2addons.crazy_preview_layer_all", "ALL"),

    RESEARCH_PEDESTAL_COMPACT("gui.crazyae2addons.research_pedestal_compact", "%s cu/t"),

    RESEARCH_OUTPUT_LABEL("gui.crazyae2addons.research_output_label", "Research Output"),
    RESEARCH_OUTPUT_DISK_NOTE("gui.crazyae2addons.research_output_disk_note", "Stored on disk"),

    RESEARCH_DRIVE_TOOLTIP_1("gui.crazyae2addons.research_drive_tooltip_1", "Research is saved on the research drive."),
    RESEARCH_DRIVE_TOOLTIP_2("gui.crazyae2addons.research_drive_tooltip_2", "It can be later used in the recipe fabricator."),

    RESEARCH_REQUIRED_COMP("gui.crazyae2addons.research_required_comp", "Required computation: %s cu"),
    RESEARCH_MIN_COMP_PER_TICK("gui.crazyae2addons.research_min_comp_per_tick", "Minimal computation: %s cu/t"),
    RESEARCH_DURATION("gui.crazyae2addons.research_duration", "Max time: %s s"),
    RESEARCH_STATION_ENERGY("gui.crazyae2addons.research_station_energy", "Power used: %s FE/t, %s FE"),
    RESEARCH_UNLOCKS("gui.crazyae2addons.research_unlocks", "Unlock: %s"),

    SPAWNER_PREVIEW_TOOLTIP("gui.crazyae2addons.spawner_preview_tooltip", "Enable/Disable preview"),
    SPAWNER_PREVIEW_LABEL("gui.crazyae2addons.spawner_preview_label", "Preview: "),
    REDSTONE_TERMINAL_KEY("key.ae2.wireless_redstone_terminal", "Open Wireless Redstone Terminal"),
    RESEARCH_FLUID_BUCKET("item.crazyae2addons.research_fluid_bucket", "Research Fluid Bucket"),
    RESEARCH_FLUID_BLOCK("block.crazyae2addons.research_fluid_block", "Research Fluid"),
    RESEARCH_FLUID_TYPE("fluid_type.crazyae2addons.research_fluid_type", "Research Fluid"),
    EC_DENSE_1K("ec.dense.1k", "1k Dense Energy Cell\ncan hold over 8G AE\n(16G FE)"),
    EC_DENSE_4K("ec.dense.4k", "4k Dense Energy Cell\ncan hold over 32G AE\n(64G FE)"),
    EC_DENSE_16K("ec.dense.16k", "16k Dense Energy Cell\ncan hold over 128G AE\n(256G FE)"),
    EC_DENSE_64("ec.dense.64k", "64k Dense Energy Cell\ncan hold over 512G AE\n(1T FE)"),
    EC_DENSE_256K("ec.dense.256k", "256k Dense Energy Cell\ncan hold over 2T AE\n(4T FE)"),
    EC_1K("ec.1k", "1k Energy Cell\ncan hold over 8M AE\n(16M FE)"),
    EC_4K("ec.4k", "4k Energy Cell\ncan hold over 32M AE\n(64M FE)"),
    EC_16K("ec.16k", "16k Energy Cell\ncan hold over 128M AE\n(256M FE)"),
    RESEARCH_PEDESTALS("gui.crazyae2addons.research_pedestals", "Pedestals"),
    RESEARCH_PEDESTAL_COMP("gui.crazyae2addons.research_pedestal_comp", "Computation: %s"),
    EC_64K("ec.64k", "64k Energy Cell\ncan hold over 512 AE\n(1G FE)"),
    EC_256K("ec.256k", "256k Energy Cell\ncan hold over 2G AE\n(4G FE)"),
    EMI_CATEGORY_MULTIBLOCKS("emi.crazyae2addons.category_multiblocks", "Crazy Multiblocks"),
    EMI_CATEGORY_CRADLE("emi.crazyae2addons.category_cradle", "Entropy Cradle Recipes"),
    EMI_CATEGORY_RESEARCH("emi.crazyae2addons.category_research", "Research Station"),
    EMI_CATEGORY_FABRICATION("emi.crazyae2addons.category_fabrication", "Recipe Fabricator"),
    JEI_CATEGORY_CRADLE("jei.crazyae2addons.category_cradle", "Entropy Cradle"),
    JEI_CATEGORY_CRAZY_MULTIBLOCKS("jei.crazyae2addons.category_crazy_multiblocks", "Crazy Multiblocks"),
    AUTO_BUILDER_PATTERN("gui.crazyae2addons.auto_builder_pattern", "Pattern"),
    AUTO_BUILDER_OFFSET("gui.crazyae2addons.auto_builder_offset", "Offset"),
    AUTO_BUILDER_MISSING_LABEL("gui.crazyae2addons.auto_builder_missing_label", "Missing:"),
    AUTO_ENCHANTER_INPUT("gui.crazyae2addons.auto_enchanter_input", "Input"),
    AUTO_ENCHANTER_OUTPUT("gui.crazyae2addons.auto_enchanter_output", "Output"),
    AUTO_ENCHANTER_XP("gui.crazyae2addons.auto_enchanter_xp", "Available XP:"),
    AUTO_ENCHANTER_LBL_CHEAP("gui.crazyae2addons.auto_enchanter_lbl_cheap", "Cheap"),
    AUTO_ENCHANTER_LBL_MEDIUM("gui.crazyae2addons.auto_enchanter_lbl_medium", "Medium"),
    AUTO_ENCHANTER_LBL_EXP("gui.crazyae2addons.auto_enchanter_lbl_exp", "Exp"),
    CRAFTING_SCHEDULER_TARGET("gui.crazyae2addons.crafting_scheduler_target", "Thing to craft"),
    DATA_DRIVE_RESEARCHES("gui.crazyae2addons.data_drive_researches", "Researches"),
    EJECTOR_CONFIG("gui.crazyae2addons.ejector_config", "Config"),
    EJECTOR_MISSING_LABEL("gui.crazyae2addons.ejector_missing_label", "Missing:"),
    FABRICATOR_INPUT("gui.crazyae2addons.fabricator_input", "Input"),
    FABRICATOR_DRIVE("gui.crazyae2addons.fabricator_drive", "Drive"),
    FABRICATOR_OUTPUT("gui.crazyae2addons.fabricator_output", "Output"),
    PENROSE_ITEM_CONSUME("gui.crazyae2addons.penrose_item_consume", "Item to consume"),
    PENROSE_MATTER_BALLS("gui.crazyae2addons.penrose_matter_balls", "Matter Balls: Power x8"),
    PENROSE_SINGULARITIES("gui.crazyae2addons.penrose_singularities", "Singularities: Power x64"),
    REDSTONE_EMITTER_LABEL_NAME("gui.crazyae2addons.redstone_emitter_label_name", "Name"),
    RESEARCH_STATION_DISK("gui.crazyae2addons.research_station_disk", "Data Disk"),
    RESEARCH_STATION_INPUTS("gui.crazyae2addons.research_station_inputs", "Inputs"),
    SPAWNER_INFO_SPEED("gui.crazyae2addons.spawner_info_speed", "Speed depends on the amount"),
    SPAWNER_INFO_CARDS("gui.crazyae2addons.spawner_info_cards", "of acceleration cards installed"),
    PORTABLE_SPATIAL_SHORT("gui.crazyae2addons.portable_spatial_short", "Portable Spatial"),
    PORTABLE_AUTOBUILDER_REQ_MATS("gui.crazyae2addons.portable_autobuilder_req_mats", "Required Materials"),
    GADGET_CLEAR("gui.crazyae2addons.gadget_clear", "Clear stored structure"),
    RESEARCH_COOLANT("gui.crazyae2addons.research_stored_coolant", "Stored coolant"),
    RESEARCH_UNIT_COMPUTATION("gui.crazyae2addons.research_unit_computation", "Providing computation: "),
    RESEARCH_UNIT_COOLANT("gui.crazyae2addons.research_unit_coolant", "Required coolant: "),
    RESEARCH_PEDESTAL_COMPUTATION("gui.crazyae2addons.research_pedestal_computation", "Connected computation: "),
    RESEARCH_PEDESTAL_INVALID("gui.crazyae2addons.research_pedestal_invalid", "Invalid connection"),
    RESEARCH_UNIT_POWER("gui.crazyae2addons.research_unit_power", "Required power: "),
    PENROSE_XEI_DESC("penrose.xei.description", "Quite a lot for one block\nand dont you need 1600?"),
    PENROSE_START_BH("gui.crazyae2addons.penrose_start_bh", "Start black hole"),
    PENROSE_BH_ON("gui.crazyae2addons.penrose_bh_on", "Active"),
    PENROSE_BH_OFF("gui.crazyae2addons.penrose_bh_off", "Inactive"),
    PENROSE_BH_STATUS("gui.crazyae2addons.penrose_bh_status", "Black hole: %s"),
    PENROSE_HEAT_EMITTER_DESIRED_HEAT("gui.crazyae2addons.penrose_heat_emitter_desired_heat", "Desired heat"),
    PENROSE_HEAT_EMITTER_SUBMIT("gui.crazyae2addons.penrose_heat_emitter_submit", "Apply heat threshold"),
    PENROSE_HEAT_VENT_COOLING("gui.crazyae2addons.penrose_heat_vent_cooling", "Heat/t"),
    PENROSE_HEAT_VENT_SUBMIT("gui.crazyae2addons.penrose_heat_vent_submit", "Apply cooling rate"),
    PENROSE_HEAT_VENT_COST("gui.crazyae2addons.penrose_heat_vent_cost", "Cost: %s FE/t"),
    PENROSE_HAWKING_VENT_RATE("gui.crazyae2addons.penrose_hawking_vent_rate", "Mass/t"),
    PENROSE_HAWKING_VENT_SUBMIT("gui.crazyae2addons.penrose_hawking_vent_submit", "Apply evaporation rate"),
    PENROSE_HAWKING_VENT_COST("gui.crazyae2addons.penrose_hawking_vent_cost", "Cost: %s FE/t"),
    PENROSE_BH_POWER("gui.crazyae2addons.penrose_bh_power", "Stored power: %s FE"),
    PENROSE_BH_MASS_DELTA("gui.crazyae2addons.penrose_bh_mass_delta", "Mass delta: %sMU/s (%s of BH mass)"),
    PENROSE_DISK_STATUS("gui.crazyae2addons.penrose_disk_status", "Disk: %s singu (%s/t), delay: %ss"),
    PENROSE_DISK_ACC_STATUS("gui.crazyae2addons.penrose_accretion_status", "Accretion: %s singu/t"),
    PENROSE_HEAT_EMITTER_ON_LABEL("gui.crazyae2addons.penrose_heat_emitter_on_label", "Emit ON at (MK):"),
    PENROSE_HEAT_EMITTER_OFF_LABEL("gui.crazyae2addons.penrose_heat_emitter_off_label", "Emit OFF at (MK):"),
    PENROSE_HEAT_EMITTER_ON_PLACEHOLDER("gui.crazyae2addons.penrose_heat_emitter_on_placeholder", "Heat ON (MK)"),
    PENROSE_HEAT_EMITTER_OFF_PLACEHOLDER("gui.crazyae2addons.penrose_heat_emitter_off_placeholder", "Heat OFF (MK)"),
    PENROSE_HEAT_EMITTER_ON_TOOLTIP("gui.crazyae2addons.penrose_heat_emitter_on_tooltip", "Start emitting when heat >= this."),
    PENROSE_HEAT_EMITTER_OFF_TOOLTIP("gui.crazyae2addons.penrose_heat_emitter_off_tooltip", "Stop emitting when heat <= this."),
    PENROSE_MASS_EMITTER_ON_LABEL("gui.crazyae2addons.penrose_mass_emitter_on_label", "Emit ON at % initial/max:"),
    PENROSE_MASS_EMITTER_OFF_LABEL("gui.crazyae2addons.penrose_mass_emitter_off_label", "Emit OFF at % initial/max:"),
    PENROSE_MASS_EMITTER_ON_PLACEHOLDER("gui.crazyae2addons.penrose_mass_emitter_on_placeholder", "ON % (e.g. 50)"),
    PENROSE_MASS_EMITTER_OFF_PLACEHOLDER("gui.crazyae2addons.penrose_mass_emitter_off_placeholder", "OFF % (e.g. 45)"),
    PENROSE_MASS_EMITTER_ON_TOOLTIP("gui.crazyae2addons.penrose_mass_emitter_on_tooltip", "Start emitting threshold."),
    PENROSE_MASS_EMITTER_OFF_TOOLTIP("gui.crazyae2addons.penrose_mass_emitter_off_tooltip", "Stop emitting threshold."),
    PENROSE_MASS_EMITTER_SUBMIT("gui.crazyae2addons.penrose_mass_emitter_submit", "Apply thresholds"),
    PENROSE_INJECTION_PORT_RATE_LABEL("gui.crazyae2addons.penrose_injection_port_rate_label", "Injection rate (singu/t):"),
    PENROSE_INJECTION_PORT_RATE_HINT("gui.crazyae2addons.penrose_injection_port_rate_hint", "0..%s"),
    PENROSE_INJECTION_PORT_RATE_TOOLTIP("gui.crazyae2addons.penrose_injection_port_rate_tooltip", "How many singularities per tick to inject from the ME network"),
    PENROSE_INJECTION_PORT_SUBMIT("gui.crazyae2addons.penrose_injection_port_submit", "Apply"),
    PENROSE_HAWKING_VENT_RATE_LABEL("gui.crazyae2addons.penrose_hawking_vent_rate_label", "Evaporation rate (MU/t):"),
    PENROSE_HAWKING_VENT_RATE_HINT("gui.crazyae2addons.penrose_hawking_vent_rate_hint", "123..."),
    PENROSE_HAWKING_VENT_RATE_TOOLTIP("gui.crazyae2addons.penrose_hawking_vent_rate_tooltip", "How much black hole mass to evaporate per tick (MU/t)."),
    PENROSE_HAWKING_VENT_SUBMIT_TOOLTIP("gui.crazyae2addons.penrose_hawking_vent_submit_tooltip", "Apply"),
    PENROSE_HAWKING_VENT_COST_LABEL("gui.crazyae2addons.penrose_hawking_vent_cost_label", "Estimated FE cost:"),
    PENROSE_HAWKING_VENT_COST_VALUE("gui.crazyae2addons.penrose_hawking_vent_cost_value", "%s FE/t"),
    PENROSE_HEAT_VENT_COOLING_LABEL("gui.crazyae2addons.penrose_heat_vent_cooling_label", "Cooling rate (MK/t):"),
    PENROSE_HEAT_VENT_COOLING_HINT("gui.crazyae2addons.penrose_heat_vent_cooling_hint", "123..."),
    PENROSE_HEAT_VENT_COOLING_TOOLTIP("gui.crazyae2addons.penrose_heat_vent_cooling_tooltip", "How much heat to remove per tick (MK/t)."),
    PENROSE_HEAT_VENT_SUBMIT_TOOLTIP("gui.crazyae2addons.penrose_heat_vent_submit_tooltip", "Apply"),
    PENROSE_HEAT_VENT_COST_LABEL("gui.crazyae2addons.penrose_heat_vent_cost_label", "Estimated FE cost:"),
    PENROSE_HEAT_VENT_COST_VALUE("gui.crazyae2addons.penrose_heat_vent_cost_value", "%s FE/t"),
    PENROSE_BH_TT_TITLE("gui.crazyae2addons.penrose_bh_tt_title", "Black hole"),
    PENROSE_BH_TT_MASS("gui.crazyae2addons.penrose_bh_tt_mass", "Mass: %s"),
    PENROSE_BH_TT_MASS_RATIO("gui.crazyae2addons.penrose_bh_tt_mass_ratio", "Fill: %s"),
    PENROSE_BH_TT_GEN("gui.crazyae2addons.penrose_bh_tt_gen", "Generation: %s FE/t"),
    PENROSE_DISK_TT_TITLE("gui.crazyae2addons.penrose_disk_tt_title", "Accretion disk"),
    PENROSE_DISK_TT_MASS("gui.crazyae2addons.penrose_disk_tt_mass", "Mass: %s"),
    PENROSE_DISK_TT_HEAT("gui.crazyae2addons.penrose_disk_tt_heat", "Heat: %s MK"),
    PENROSE_DISK_TT_FE_DISK("gui.crazyae2addons.penrose_disk_tt_fe_disk", "FE remaining in disk: %s"),
    PENROSE_TITLE_BLACK_HOLE("gui.crazyae2addons.penrose_title_black_hole", "Black Hole"),
    PENROSE_TITLE_ACCRETION_DISK("gui.crazyae2addons.penrose_title_accretion_disk", "Accretion Disk"),
    PENROSE_TITLE_PREVIEW("gui.crazyae2addons.penrose_title_preview", "Penrose Preview"),
    PENROSE_TITLE_MASS("gui.crazyae2addons.penrose_title_mass", "Mass"),
    PENROSE_TITLE_HEAT("gui.crazyae2addons.penrose_title_heat", "Heat"),

    PENROSE_LINE_DISK_MASS("gui.crazyae2addons.penrose_line_disk_mass", "Disk mass: %s MU"),
    PENROSE_LINE_HEAT_MK("gui.crazyae2addons.penrose_line_heat_mk", "Heat: %s MK"),
    PENROSE_LINE_GEN_T_FE("gui.crazyae2addons.penrose_line_gen_t_fe", "Gen/t: %s FE/t"),
    PENROSE_LINE_USE_T_FE("gui.crazyae2addons.penrose_line_use_t_fe", "Use/t: %s FE/t"),
    PENROSE_LINE_FE_IN_DISK("gui.crazyae2addons.penrose_line_fe_in_disk", "FE in disk: %s FE"),

    PENROSE_OVERLAY_BH_MASS("gui.crazyae2addons.penrose_overlay_bh_mass", "BH mass: %s MU"),
    PENROSE_OVERLAY_DISK_MASS("gui.crazyae2addons.penrose_overlay_disk_mass", "Disk mass: %s MU"),
    PENROSE_OVERLAY_GEN("gui.crazyae2addons.penrose_overlay_gen", "Gen/t: %s FE"),
    PENROSE_OVERLAY_USE("gui.crazyae2addons.penrose_overlay_use", "Use/t: %s FE"),
    PENROSE_OVERLAY_FE_STORED("gui.crazyae2addons.penrose_overlay_fe_stored", "FE stored: %s FE"),
    PENROSE_OVERLAY_FE_IN_DISK("gui.crazyae2addons.penrose_overlay_fe_in_disk", "FE in disk: %s FE"),
    PENROSE_MASS_BAR("gui.crazyae2addons.penrose_mass_bar", "Mass: %s"),
    PENROSE_HEAT_BAR("gui.crazyae2addons.penrose_heat_bar", "Heat: %s/%s MK"),
    PENROSE_MASS_CURRENT_MU("gui.crazyae2addons.penrose_mass_current_mu", "Current: %s MU"),
    PENROSE_MASS_INITIAL_MU("gui.crazyae2addons.penrose_mass_initial_mu", "Initial: %s MU"),
    PENROSE_MASS_MAX_MU("gui.crazyae2addons.penrose_mass_max_mu", "Max: %s MU"),
    PENROSE_HEAT_CURRENT_MK("gui.crazyae2addons.penrose_heat_current_mk", "Current: %s MK"),
    PENROSE_HEAT_MAX_MK("gui.crazyae2addons.penrose_heat_max_mk", "Max: %s MK"),
    PENROSE_EFFICIENCY("gui.crazyae2addons.penrose_efficiency", "Efficiency: %s"),
    WIRELESS_NOTIF_ADD_ROW("gui.crazyae2addons.notification_terminal_add_row", "Add new row"),
    WIRELESS_NOTIF_THRESHOLD_NEED_FILTER("gui.crazyae2addons.notification_terminal.threshold_need_filter","Set resource to determine the limits unit."),
    WIRELESS_NOTIF_THRESHOLD_UNIT("gui.crazyae2addons.notification_terminal.threshold_unit","Threshold unit: %s"),
    WIRELESS_NOTIF_THRESHOLD_UNIT_INTERNAL("gui.crazyae2addons.notification_terminal.threshold_unit_internal","Threshold unit: %s (1 %s = %s internal)"),
    STOCK_TOAST_TITLE("gui.crazyae2addons.toast.stock_alert_title", "AE2 Stock Alert"),
    STOCK_TOAST_ABOVE("gui.crazyae2addons.toast.stock_alert_above","Went above %s threshold (now %s)"),
    STOCK_TOAST_BELOW("gui.crazyae2addons.toast.stock_alert_below","Fell below %s threshold (now %s)"),
    WIRELESS_NOTIF_UNIT_LINE("gui.crazyae2addons.notification_terminal.unit_line", "Unit: %s"),
    PENROSE_HEAT_CURRENT("gui.crazyae2addons.penrose_heat_current_gk", "Current heat: %s MK"),
    PENROSE_HEAT_MAX("gui.crazyae2addons.penrose_heat_max_gk", "Max heat: %s MK"),
    AMOUNT_UNIT_INT("gui.crazyae2addons.amount.unit_int", "%s %s"),
    AMOUNT_UNIT_DEC_INTERNAL("gui.crazyae2addons.amount.unit_decimal_with_internal", "%s %s (%s)"),
    MODIFIER_MULT_X2("gui.crazyae2addons.modifier_mult_x2", "x2"),
    MODIFIER_MULT_DIV2("gui.crazyae2addons.modifier_mult_div2", "/2"),
    MODIFIER_MULT_X2_TOOLTIP("gui.crazyae2addons.modifier_mult_x2_tooltip", "Multiply pattern x2"),
    MODIFIER_MULT_DIV2_TOOLTIP("gui.crazyae2addons.modifier_mult_div2_tooltip", "Divide pattern /2"),
    MODIFIER_INFO_IGNORE_NBT("gui.crazyae2addons.modifier_info_ignore_nbt", "Current: ignore NBT"),
    MODIFIER_INFO_DO_NOT_IGNORE_NBT("gui.crazyae2addons.modifier_info_do_not_ignore_nbt", "Current: Do not ignore NBT"),
    MODIFIER_CIRCUIT_NONE("gui.crazyae2addons.modifier_circuit_none", "No circuit selected"),
    MODIFIER_CIRCUIT_SELECTED("gui.crazyae2addons.modifier_circuit_selected", "Selected circuit %s"),
    MODIFIER_CIRCUIT_BUTTON("gui.crazyae2addons.modifier_circuit_button", "%s"),
    MULTI_EMITTER_LOGIC("gui.crazyae2addons.multi_emitter.logic", "Switch logic (OR / AND)"),
    MULTI_EMITTER_UNIT_LINE("gui.crazyae2addons.multi_emitter.unit_line", "Unit: %s"),
    MULTI_EMITTER_CMP_ABOVE("gui.crazyae2addons.multi_emitter.cmp_above", "Emit when amount is above or equal to limit"),
    MULTI_EMITTER_CMP_BELOW("gui.crazyae2addons.multi_emitter.cmp_below", "Emit when amount is bellow limit"),
    MODIFIER_IGNORE_NBT_TOOLTIP("gui.crazyae2addons.modifier_ignore_nbt_tooltip", "Toggle ignore NBT option"),
    CRAFTING_SCHEDULER_TOOLTIP("gui.crazyae2addons.c_scheduler_amount_tt", "How much to request (mB for fluids)"),
    PENROSE_BH_MASS_HEAT("gui.crazyae2addons.penrose_bh_mass_heat", "Mass: %s MU | Heat: %s");


    private final String key;
    private final String value;

    LangDefs(String key, String value) {
        this.key = key;
        this.value = value;
    }

    @Override
    public String getTranslationKey() {
        return key;
    }

    @Override
    public String getEnglishText() {
        return value;
    }
}
